import { atomWithReset, freezeAtomCreator } from 'jotai/utils';
import { DEFAULT_PAGE_SIZE, TAB_LOG } from './const';

const _freeze = freezeAtomCreator(atomWithReset);
const _atom = (init, freeze = true) => freeze ? _freeze(init) : atomWithReset(init);

export const tooltip_info = _atom({});
export const my_toast = _atom(null);
export const signal_r = _atom(false);
export const new_smf_requests = _atom([]);
export const my_wait = _atom(false);
export const use_aladdin = _atom(true);
export const as_of_date = _atom(null);
export const date_picker_visible = _atom(false);
export const auth_info = _atom({});
export const selected_tab = _atom(TAB_LOG);
export const can_post_to_trading = _atom(false);
export const include_trades = _atom(false);
export const include_orders = _atom(false);
export const column_selector_on = _atom(false);
export const column_selector_search = _atom({});
export const column_order = _atom(null);
export const show_runs = _atom(true);
export const show_exports = _atom(true);
export const show_sso = _atom(false);
export const security_id = _atom(null);
export const can_save_filters = _atom(false);
export const show_filter_help = _atom(false);
export const edit_settings = _atom(false);
export const show_all_history = _atom(false);
export const my_sleeves = _atom(null);
export const log_filter = _atom(null);
export const master_log = _atom(null);
export const selected_log_item = _atom(null);
export const log_page_size = _atom(DEFAULT_PAGE_SIZE);
export const history_page_size = _atom(DEFAULT_PAGE_SIZE);
export const page_size = _atom(DEFAULT_PAGE_SIZE);
export const comp_selector_page_size = _atom(DEFAULT_PAGE_SIZE);
export const comp_page_size = _atom(DEFAULT_PAGE_SIZE);
export const run_table_page_size = _atom(DEFAULT_PAGE_SIZE);
export const sleeve_filter = _atom(null);
export const timer_ticks = _atom(null);
export const column_metadata = _atom(null);
export const run_column_metadata = _atom(null);
export const comp_column_metadata = _atom(null);
export const optim_column_sizes = _atom({});
export const run_column_sizes = _atom({});
export const comp_column_sizes = _atom({});
export const trading_list = _atom([]);
export const run_trading_list = _atom([]);
export const run_fetching = _atom(false);
